---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-backup-configmap
data:
  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "vault"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/appuser/.aws/token"
          "mode" = 0644
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = true

    "template" = {
      "contents" = 
        "{{- with secret \"secret/data/aws/awscreds_s3\" -}}\n[default]\naws_access_key_id = {{ .Data.data.AWS_ACCESS_KEY_ID }}\naws_secret_access_key = {{ .Data.data.AWS_SECRET_ACCESS_KEY }}\n{{- end -}}"
      
      "destination" = "/home/appuser/.aws/credentials"
    }

    "vault" = {
      "address" = "http://vault-active.vault.svc.cluster.local:8200"
    }

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: vaultbackup
spec:
  concurrencyPolicy: Forbid
  schedule: "* * * * *"
  # schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: "true"
            vault.hashicorp.com/agent-configmap: "vault-backup-configmap"
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/secret-volume-path: "/home/appuser/.aws"
        spec:
          serviceAccountName: vault
          containers:
          - name: vaultbackup
            image: samgabrail/tekanaid_vault_backup
            imagePullPolicy: Always
            env:
              - name: VAULT_ADDR
                value: http://vault-active.vault.svc.cluster.local:8200
              - name: S3BUCKET
                value: tekanaid-vault-backup-demo1
          restartPolicy: OnFailure
